### ISSUE TITLE
70B GGML Model Fails to load

### ISSUE THREAD

**Issue by wolfpack12** [R3gm/ConversaDocs#1]
**Using this HF repo:** https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGML
**Model:** llama-2-70b-chat.ggmlv3.q4_K_M.bin (Although this was attempted with several)

Downloading (…)at.ggmlv3.q4_K_M.bin: 100%|█| 41.4G/41.4G [13:25<00:00, 51.4MB/s]
llama.cpp: loading model from /home/user/.cache/huggingface/hub/models--TheBloke--Llama-2-70B-Chat-GGML/snapshots/54b9a6dc10c70d9de57244370690d9ac71aa2c32/llama-2-70b-chat.ggmlv3.q4_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 4096
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_head_kv  = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 24576
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: model size = **65B**
llama_model_load_internal: ggml ctx size =    0.21 MB
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
llama_load_model_from_file: failed to load model

Model size of 65B looked odd. The 7B and 13B models report correctly.

**Comment by R3gm** [comment]
Thank you for reporting this issue, @wolfpack12.

I'm glad to inform you that the loading error for the 70B models has been addressed and resolved in commit "ad4ab66." 

If you encounter any further issues or have questions, please feel free to ask.

Appreciate your patience and contribution.
